title: 社内ドキュメントサイト
description: 社内で管理するサービス設計・要件ドキュメント

# Markdownの処理
markdown: kramdown
kramdown:
  input: GFM

# 公開対象のファイル
include:
  - docs
  - all-docs.html

# GitHub Pagesで使うsafe mode向け
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
